#!/usr/bin/gawk -E

# Autor: Ulpiano Tur de Vargas <ulpiano.tur.devargas@gmail.com>
#
# Este programa es software libre; puedes distribuirlo y/o
# modificarlo bajo los términos de la Licencia Pública General de GNU
# según la publicó la Fundación del Software Libre; ya sea la versión 3, o
# (a su elección) una versión superior.
#
# Este programa se distribuye con la esperanza de que sea útil,
# pero SIN NINGUNA GARANTIA; ni siquiera la garantía implícita de
# COMERCIABILIDAD o APTITUD PARA UN PROPÓSITO DETERMINADO. Vea la
# Licencia Pública General de GNU para más detalles.
#
# Deberías haber recibido una copia de la Licencia Pública General
# de GNU junto con este software; mira el fichero LICENSE. Si
# no, mira <https://www.gnu.org/licenses/>.

# Author: Ulpiano Tur de Vargas <ulpiano.tur.devargas@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 3, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this software; see the file LICENSE. If
# not, see <https://www.gnu.org/licenses/>.

@include "bbl_jdva.awk";

BEGIN {
    delete lista;
    pon(lista, "identificación.nombre", "Pedro");
    pon(lista, "identificación.apellidos", "Blanco Crespo");
    pon(lista, "identificación.edad", 17);
    pon(lista, "domicilio.pais", "España");
    pon(lista, "domicilio.autonomía", "Comunidad de Madrid");
    pon(lista, "domicilio.provincia", "Madrid");
    pon(lista, "domicilio.población", "Madrid");
    pon(lista, "domicilio.localización.1", 10.11);
    pon(lista, "domicilio.localización.2", 10.22);
    pon(lista, "domicilio.dirección.tipo", "Calle");
    pon(lista, "domicilio.dirección.calle", "Jacometrezo");
    pon(lista, "domicilio.dirección.número", 32);
    pon(lista, "domicilio.dirección.bloque", 1);

    if (ARGC > 1)
        usar();

    cad_json[0] = "";
        
    lstmJson(lista, cad_json);
    
    sangra(cad_json);
    
    exit 0;
}

function usar()
{
    printf "%s\n\n%s\n%s\n\n",
    "Usar: crea_json [--ayuda]",
    "Pinta por pantalla un texto en formato JSON, creado a partir de la", 
    "siguiente lista multidimensional:";
    
    pinta(lista);
    
    exit -1;
}