#!/usr/bin/gawk -E

@include "../src/ecma-404.awk"

BEGIN {
    if (ARGC == 1 || 
        ARGC > 2 || 
        ARGV[1] == "--ayuda" ||
        ARGV[1] !~ /^\.\.\/pruebas\/ejemplo_[0-9]{2}\.json$/)
        usar();
        
    cad_json[0] = "";
    linea = "";

    while ((getline linea < ARGV[1]) > 0)
        cad_json[0] = cad_json[0] linea;
    close(ARGV[1]);
    
    jsonLstm(cad_json, lista);
    
    pinta(lista);
   
    exit 0;
}

function usar()
{
    printf "%s\n\n%s\n%s\n%s\n",
    "usar: pinta_lista [--ayuda] <../pruebas/ejemplo_XX.json>",
    "Pinta por pantalla la representación de una lista multidimensional",
    "jotasonizada, creada a partir de un texto en formato JSON contenido",
    "dentro del fichero que se le pasa como argumento.";
    exit -1;
}